donggyunhuh/TeamProjectFlower_Sourcecode

src/main/java/org/flower/entities/Flower.java
src/main/java/org/flower/entities/FlowerImage.java

flowerinfo, floweriamge 엔티티 추가

---

src/main/java/org/flower/entities/User.java
src/main/java/org/flower/models/Order/FlowerOrder.java

model 폴더 추가

---

src/main/java/org/flower/controllers/user/user/UserJoin.java
src/main/java/org/flower/models/user/UserJoinService.java

join 기능 구현중

---

src/main/java/org/flower/configs/SecurityConfig.java

SecurityConfig수정

---

src/main/java/org/flower/configs/SecurityConfig.java
src/main/java/org/flower/models/user/LoginFailureHandler.java
src/main/java/org/flower/models/user/LoginSuccessHandler.java
src/main/resources/templates/error/401.html
src/main/resources/templates/error/403.html
src/main/resources/templates/error/404.html
src/main/resources/templates/error/500.html
src/main/resources/templates/error/_message.html
src/main/resources/templates/error/common.html

로그인 기능 일부 추가

---

src/main/java/org/flower/commons/UserUtils.java
src/main/java/org/flower/models/user/UserEditService.java
src/main/java/org/flower/models/user/UserSaveService.java
src/main/resources/static/front/recommend/js/common.js
src/main/resources/templates/front/mypage/main/home.html
src/main/resources/templates/front/outlines/header.html

UserSaveService 구현 완료

---

src/main/java/org/flower/commons/validators/PasswordValidator.java
src/main/java/org/flower/configs/AuditorAwareImpl.java
src/main/java/org/flower/controllers/user/user/LoginController.java

AuditorAwareImpl 추가

---

src/main/java/org/flower/commons/validators/RequiredCheckValidator.java
src/main/java/org/flower/commons/validators/ServiceValidator.java
src/main/resources/templates/front/user/join.html

validator 추가

---

src/main/java/org/flower/commons/Pagination.java
src/main/resources/templates/commoms/pagenation.html

pagination 추가

---

src/main/java/org/flower/repositories/FlowerRepository.java

flowerrepository 추가

---

src/main/java/org/flower/commons/validators/NickNameCheckValidator.java
src/main/java/org/flower/commons/validators/PasswordValidator.java
src/main/java/org/flower/commons/validators/RequiredCheckValidator.java
src/main/java/org/flower/controllers/user/user/JoinController.java
src/main/java/org/flower/controllers/user/user/UserJoinValidator.java
src/main/java/org/flower/entities/User.java
src/main/java/org/flower/repositories/UserRepository.java
src/main/resources/messages/validation.properties
src/main/resources/static/front/css/user/style.css
src/main/resources/static/front/js/common.js
src/main/resources/templates/front/layouts/main.html
src/main/resources/templates/front/user/_form.html

회원가입 유효성 검사 완료

---

src/main/java/org/flower/controllers/admin/user/UserController.java
src/main/java/org/flower/entities/BaseEntity.java
src/main/java/org/flower/entities/BaseUserEntity.java
src/main/java/org/flower/entities/User.java
src/main/resources/static/admin/css/style.css
src/main/resources/templates/admin/user/index.html

관리자 회원목록 css 완료

---

src/main/java/org/flower/controllers/admin/recommend/RecoMegmentController.java
src/main/java/org/flower/controllers/admin/user/UserController.java
src/main/java/org/flower/controllers/recommend/RecommendController.java
src/main/java/org/flower/models/recommend/FlowerReccomend.java
src/main/java/org/flower/models/recommend/flower/flowerInfo.java
src/main/java/org/flower/models/recommend/keyword/KeywordDeleteService.java
src/main/java/org/flower/models/recommend/keyword/KeywordInfo.java
src/main/java/org/flower/models/recommend/keyword/KeywordInfoService.java
src/main/java/org/flower/models/recommend/keyword/KeywordSaveService.java
src/main/java/org/flower/models/user/UserInfoService.java
src/main/java/org/flower/repositories/KeywordRepository.java
src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/recommend/keyword.html

키워드 추가 기능 완료

---

src/main/java/org/flower/controllers/admin/recommend/RecoMegmentController.java
src/main/java/org/flower/models/recommend/keyword/KeywordEditService.java
src/main/java/org/flower/models/recommend/keyword/KeywordInfoService.java
src/main/java/org/flower/models/recommend/keyword/KeywordSaveService.java
src/main/java/org/flower/repositories/KeywordRepository.java
src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/recommend/keyword.html

고려해야할 점(키워드 번호가 ID 값으로 설정되어 있어 불변성을 지켜야 하기 때문에 키워드를 삭제할 경우 번호가 들쭉날쭉하게 됨)

키워드 수정, 삭제 기능 추가 완료

---

src/main/java/org/flower/entities/FlowerKeywordMapping.java
src/main/resources/templates/admin/order/index.html
src/main/resources/templates/admin/recommend/flowerWeight.html

플라워키워드엔티티중에서 꽃 이름, 키워드 이름까지 불러올 수 있게 수정
회원 상세 정보의 경로를 userInfo로 수정

플라워키워드엔티티 수정

---

src/main/resources/templates/admin/order/index.html

주문 추가 후 성공 or 실패 메세지 출력 기능 추가

---

src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/order/index.html
src/main/resources/templates/admin/recommend/keyword.html
src/main/resources/templates/admin/user/index.html

리스트 체크박스 전체 선택 기능 추가

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/models/order/order/OrderEditService.java
src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/order/index.html
src/main/resources/templates/admin/recommend/keyword.html

주문 리스트 수정 작업 진행중

---

src/main/java/org/flower/controllers/admin/recommend/RecoMegmentController.java
src/main/java/org/flower/models/recommend/keyword/KeywordDeleteService.java
src/main/resources/templates/admin/recommend/keyword.html

관리자 페이지 키워드 추가, 수정, 삭제 버그 수정 완료

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/controllers/user/user/JoinController.java
src/main/java/org/flower/models/order/order/OrderEditInfo.java
src/main/java/org/flower/models/order/order/OrderEditService.java
src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/order/index.html

관리자페이지 주문 목록 수정 기능 완성

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/controllers/admin/recommend/FlowerController.java
src/main/java/org/flower/controllers/admin/recommend/FlowerWeightController.java
src/main/java/org/flower/controllers/admin/recommend/KeywordController.java

기능 마다 따로 컨트롤러를 세분화 해서 유지 보수에 유용하게 함

관리자 recommend Controller 세분화

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/models/order/order/OrderEditService.java
src/main/resources/static/admin/js/common.js
src/main/resources/templates/admin/order/index.html

관리자 페이지 주문 리스트 삭제 기능 완성

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/controllers/admin/order/StoreController.java
src/main/java/org/flower/entities/OrderStoreMapping.java
src/main/java/org/flower/entities/Store.java
src/main/java/org/flower/models/order/order/OrderInfoService.java
src/main/java/org/flower/models/order/store/StoreInfo.java
src/main/java/org/flower/models/order/store/StoreInfoService.java
src/main/java/org/flower/repositories/StoreRepository.java
src/main/resources/templates/admin/order/store.html

관리자페이지 - 주문관리 페이지의 매장 목록 리스트 구현

---

src/main/java/org/flower/controllers/admin/order/StoreController.java
src/main/java/org/flower/entities/Store.java
src/main/java/org/flower/models/order/store/StoreEditInfo.java
src/main/java/org/flower/models/order/store/StoreEditService.java
src/main/java/org/flower/models/order/store/StoreInfoService.java
src/main/java/org/flower/repositories/UserRepository.java
src/main/resources/templates/admin/order/_submenu.html
src/main/resources/templates/admin/order/addstorelist.html
src/main/resources/templates/admin/order/store.html

StoreInfo, StoreInfoService
StoreEditInfo, StoreEditService 클래스를 생성하고, 매장 추가 기능을 구현함. 삭제와 수정 기능은 앞으로의 개발이 필요

Dokyoung - 관리자 페이지의 주문관리 기능 - 매장 추가 기능 구현

---

src/main/resources/static/front/css/style.css
src/main/resources/static/front/recommend/css/style.css
src/main/resources/templates/front/recommend/flower.html

데이터 베이스에서 값 받아오기까지 성공, css 부분 조금만 손 보면 됨

front 꽃 추천 페이지 기능 구현중

---

src/main/java/org/flower/controllers/user/mypage/profile/ProfileController.java
src/main/java/org/flower/controllers/user/user/UserEdit.java
src/main/java/org/flower/controllers/user/user/UserEditValidator.java
src/main/java/org/flower/models/user/UserEditInfo.java
src/main/java/org/flower/models/user/UserEditService.java
src/main/resources/static/front/mypage/css/style.css
src/main/resources/templates/front/mypage/main/home.html
src/main/resources/templates/front/mypage/profile/profilePage.html

UserEdit, UserEditValidator, UserEditInfo, UserEditService 추가

UserEdit, UserEditValidator, UserEditInfo, UserEditService 추가

---

src/main/resources/static/front/recommend/css/style.css

폰트 적용 위치 변경

---

src/main/java/org/flower/configs/SecurityConfig.java
src/main/java/org/flower/controllers/user/mypage/profile/NicknameEditController.java
src/main/java/org/flower/controllers/user/mypage/profile/UserProfileController.java
src/main/java/org/flower/models/user/UserEditInfoService.java
src/main/java/org/flower/models/user/UserEditService.java
src/main/java/org/flower/repositories/UserRepository.java
src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/profile/profilePage.html

403 오류 해결 아직 못함

---

src/main/resources/static/front/recommend/css/style.css
src/main/resources/static/front/recommend/js/common.js
src/main/resources/templates/front/recommend/main.html

front 키워드 선택 부분 css 수정 중

---

src/main/java/org/flower/controllers/user/mypage/profile/UserProfileController.java
src/main/java/org/flower/models/user/UserEditService.java
src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/profile/profilePage.html

닉네임 수정 기능 추가 완료
반영하려면 다시 로그인해야함
추후에 세션 업데이트 코드 추가하여 닉네임 수정시 바로 적용되게 할 예정

닉네임 수정 기능 구현

---

src/main/java/org/flower/controllers/user/mypage/orderlist/OrderNickController.java
src/main/java/org/flower/models/user/mypage/OrderListService.java
src/main/resources/static/front/mypage/css/style.css
src/main/resources/templates/front/mypage/main/home.html
src/main/resources/templates/front/mypage/main/home_orderlist.html

주문 내역 html 까지 완성

---

src/main/resources/templates/admin/order/index.html
src/main/resources/templates/admin/recommend/flowerWeightList.html
src/main/resources/templates/admin/recommend/index.html
src/main/resources/templates/admin/recommend/keyword.html

주문리스트, 꽃리스트, 키워드리스트, 꽃키워드 가중치 리스트를 전체 선택하도록 함수를 추가함

관리자페이지에서 항목을 전체선택 가능하도록 수정

---

src/main/resources/templates/admin/recommend/flowerWeightList.html
src/main/resources/templates/admin/recommend/index.html
src/main/resources/templates/admin/recommend/keyword.html

주문 리스트 빼고 꽃리스트, 키워드리스트, 가중치리스트의 전체선택기능을 삭제

---

src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/controllers/user/mypage/orderlist/OrderNickController.java
src/main/java/org/flower/models/order/order/OrderInfo.java
src/main/java/org/flower/models/order/order/OrderInfoService.java
src/main/java/org/flower/repositories/OrderRepository.java
src/main/resources/static/front/mypage/css/style.css
src/main/resources/templates/front/mypage/main/home.html
src/main/resources/templates/front/mypage/main/home_orderlist.html
src/main/resources/templates/front/order/orderCompleted.html

마이페이지 주문내역 보기 기능 추가, 주문일시 가독성있게 2023-11-04 형식으로 변경

마이페이지 주문내역 기능 추가

---

src/main/resources/static/front/mypage/css/style.css
src/main/resources/static/front/order/css/style.css

주문서 작성 페이지 css수정

---

src/main/resources/static/front/order/css/style.css
src/main/resources/static/front/recommend/css/style.css
src/main/resources/templates/front/recommend/main.html

front 꽃 추천 부분 css 적용 완료

---

src/main/java/org/flower/controllers/postCard/OpenAIController.java
src/main/java/org/flower/models/postCard/OpenAiInfo.java
src/main/resources/application.properties
src/main/resources/templates/front/postcard/result.html

이미지 url가져오는 데 성공했으나, view부분에 출력하지는 못함

Dalle 2 api 가져오기 성공

---

src/main/resources/application.properties
src/main/resources/static/front/postcard/css/style.css
src/main/resources/templates/front/layouts/main.html
src/main/resources/templates/front/postcard/result.html

postcard 부분 간단한 css

---

src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/models/order/order/OrderInfoService.java
src/main/java/org/flower/models/user/UserInfo.java
src/main/java/org/flower/repositories/OrderRepository.java
src/main/resources/templates/front/mypage/layouts/duplication.html
src/main/resources/templates/front/mypage/main/orderList_Owner.html

마이페이지 주문 확인 대기 수 동적 업데이트

---

src/main/resources/application.properties
src/main/resources/static/front/postcard/css/style.css
src/main/resources/templates/front/postcard/main.html
src/main/resources/templates/front/postcard/result.html
src/main/resources/templates/front/recommend/flower.html

꽃 결과 화면에서 엽서 만들기 기능으로 가는 버튼 만들고, 보고서 제출을 위해 요소 중앙으로 오도록 css 수정

postcard 부분 css 간단하게 수정

---

src/main/java/org/flower/commons/constants/OrderState.java
src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/models/user/UserInfo.java
src/main/java/org/flower/models/user/UserInfoService.java
src/main/resources/static/front/mypage/css/style.css
src/main/resources/templates/front/mypage/main/orderList_Owner.html

role이 OWNER 이면 사장님 주문내역페이지 보여줌, OWNER가 아니면 기본 주문 페이지.

사장님 주문내역 페이지

---

src/main/java/org/flower/controllers/admin/order/OrderController.java
src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/models/order/order/OrderEditService.java
src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/layouts/duplication.html
src/main/resources/templates/front/mypage/main/home_orderlist.html
src/main/resources/templates/front/mypage/main/orderList_Owner.html
src/main/resources/templates/front/outlines/header.html

주문접수 버튼 누르면 ACCEPTING -> ACCEPTED 로 변경
화면 확인 대기, 확인 완료 숫자 동적으로 변경

OWNER 계정 마이페이지

---

src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/layouts/duplication_profile.html

닉네임 변경 요소 추가

---

src/main/java/org/flower/controllers/user/mypage/profile/ProfileController.java
src/main/resources/static/front/mypage/js/common.js

닉네임 수정시 즉시 반영되게

---

src/main/resources/static/front/mypage/css/style.css
src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/layouts/duplication_profile.html
src/main/resources/templates/front/mypage/profile/profilePage.html

닉네임 변경 js, html 수정

---

src/main/java/org/flower/configs/SecurityConfig.java
src/main/java/org/flower/controllers/user/mypage/profile/ProfileController.java
src/main/resources/static/front/mypage/css/style.css
src/main/resources/templates/front/mypage/layouts/duplication.html
src/main/resources/templates/front/mypage/main/passwordConfirm.html

로그인한 사용자의 비밀번호와 입력한 비밀번호 비교 후 페이지 리다이렉트하는 로직

비밀번호 확인 페이지 완료

---

src/main/java/org/flower/controllers/postCard/OpenAIController.java

dalle 기본 프롬프트 조금 수정

---

src/main/resources/static/front/css/style.css

order 폼이 푸터와 곂치는 현상 없앰( 다른 모니터로도 확인해볼 예정)

front 부분 css 수정 완료

---

src/main/resources/static/front/order/js/common.js
src/main/resources/templates/front/order/orderForm.html

1. 픽업 날짜와 시간 검증: 사용자가 픽업 날짜와 시간을 선택하지 않았을 경우, 각각 '픽업 날짜를 선택해주세요.' 및 '픽업 시간을 선택해주세요.'라는 경고 메시지를 표시합니다.
2. 꽃 선택 검증: 사용자가 꽃을 선택하지 않았을 경우, '주문하실 꽃을 선택해주세요.'라는 경고 메시지를 표시합니다. 이를 위해 모든 꽃 선택 input 태그에서 checked 상태를 확인합니다.

주문서 폼 제출 전 필수 입력 항목 검증 기능 개선

---

src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/models/order/order/OrderInfoService.java
src/main/resources/static/front/mypage/js/common.js
src/main/resources/templates/front/mypage/layouts/duplication.html
src/main/resources/templates/front/mypage/main/orderList_Owner.html
src/main/resources/templates/front/outlines/header.html

사장님 마이페이지에서 주문 개수 누르면 각 주문상태의 주문만 모아서 볼 수 있음

주문 상태별로 확인

---

src/main/java/org/flower/controllers/postCard/OpenAIController.java
src/main/resources/static/front/postcard/css/style.css
src/main/resources/templates/front/postcard/result.html

달리 결과창 css 수정 완료

---

src/main/java/org/flower/controllers/user/mypage/MypageHomeController.java
src/main/java/org/flower/models/order/order/OrderInfoService.java

개인 마이페이지에서 다른 사람의 주문까지 확인할 수 있는 오류 수정

긴급한 오류 / 마이페이지 컨트롤러
